### ISSUE TITLE
Question about the client ASG

### ISSUE THREAD

**Issue by rbolkey** [aws-quickstart/quickstart-hashicorp-consul#12]
Hi,

Is there a reason that the ConsulClientAsg has a minimum size equal to the number of consul server nodes? I'm trying to understand if I can safely remove the client nodes from the stack completely (with the goal of deploying them separately as part of my application's ASG).

Thanks!
Rick

**Comment by avattathil** [comment]
That was a bug,  I pushed a fix
https://github.com/aws-quickstart/quickstart-hashicorp-consul/blob/master/templates/quickstart-hashicorp-consul.template#L358

Thanks
--Tony
