### ISSUE TITLE
BastionAutoScalingGroup  FAILURE

### ISSUE THREAD

**Issue by victoremmanuel** [aws-quickstart/quickstart-hashicorp-consul#19]
DELETE_COMPLETE	AWS::Logs::MetricFilter	SSHMetricFilter	
DELETE_IN_PROGRESS	AWS::AutoScaling::AutoScalingGroup	BastionAutoScalingGroup	
DELETE_IN_PROGRESS	AWS::Logs::MetricFilter	SSHMetricFilter	
DELETE_IN_PROGRESS	AWS::CloudFormation::Stack	HashiCorp-Consul-BastionStack-	User Initiated
CREATE_FAILED	AWS::CloudFormation::Stack	HashiCorp-Consul-BastionStack	
The following resource(s) failed to create: [BastionAutoScalingGroup].
CREATE_FAILED	AWS::AutoScaling::AutoScalingGroup	BastionAutoScalingGroup	Received 1 FAILURE signal(s) out of 1. Unable to satisfy 100% MinSuccessfulInstancesPercent requirement

**Comment by victoremmanuel** [comment]
Failure is in the below stack
AWS::CloudFormation::Stack	HashiCorp-Consul-BastionStack

**Comment by avattathil** [comment]
Did you launch it from a local clone ?

**Comment by avattathil** [comment]
Submodules were updated. Please reopen it the issue presists
