### ISSUE TITLE
Unable to launch in London

### ISSUE THREAD

**Issue by jmkgreen** [aws-quickstart/quickstart-hashicorp-consul#23]
Any chance of getting AMIs across a broader set of regions? We would need London for legal regulation reasons.

**Comment by avattathil** [comment]
Apologies for the delay added in https://github.com/aws-quickstart/quickstart-hashicorp-consul/commit/8c5eb5cc9355b619800888c061eb715d34bcca8f

**Comment by avattathil** [comment]
https://github.com/aws-quickstart/quickstart-hashicorp-consul/pull/31
