### ISSUE TITLE
Removal of scripts directory broke the AWS Quickstart Cloudformation for Vault

### ISSUE THREAD

**Issue by brian-uplevel** [aws-quickstart/quickstart-hashicorp-consul#32]
> wget https://s3.amazonaws.com/${QSS3BucketName}/${QSS3KeyPrefix}submodules/quickstart-hashicorp-consul/scripts/consul_client_bootstrap.sh\n

This line in the CloudFormation template for vault is broken as a result of a submodule dependency on this repository.

**Comment by avattathil** [comment]
@brian-uplevel thanks for reporting this configset bug is addresed here https://github.com/aws-quickstart/quickstart-hashicorp-consul/pull/34

**Comment by avattathil** [comment]
Fix in master, Closing
