### ISSUE TITLE
Misaligned Yaml File

### ISSUE THREAD

**Issue by hhshih** [aws-quickstart/quickstart-hashicorp-consul#33]
https://github.com/aws-quickstart/quickstart-hashicorp-consul/blob/95efb75f6e5ab106ccf7e8c460ede69e3d9ac954/templates/quickstart-hashicorp-consul.template#L310

https://github.com/aws-quickstart/quickstart-hashicorp-consul/blob/95efb75f6e5ab106ccf7e8c460ede69e3d9ac954/templates/quickstart-hashicorp-consul.template#L493

These lines are misaligned (having the same indent as `file`), 
causing the files to be missing in the created instances, and thus the template does not work.

Also, the curly braces seems to be reversed in the following lines.
https://github.com/aws-quickstart/quickstart-hashicorp-consul/blob/95efb75f6e5ab106ccf7e8c460ede69e3d9ac954/templates/quickstart-hashicorp-consul.template#L495
https://github.com/aws-quickstart/quickstart-hashicorp-consul/blob/95efb75f6e5ab106ccf7e8c460ede69e3d9ac954/templates/quickstart-hashicorp-consul.template#L501

**Comment by avattathil** [comment]
@hhshih care to contribute this change via PR ? Appreciate you troubleshooting this!

**Comment by hhshih** [comment]
Sure! I'm provisioning with the modified template currently. Will file a PR when it's verified.

**Comment by hhshih** [comment]
https://github.com/aws-quickstart/quickstart-hashicorp-consul/pull/34

**Comment by avattathil** [comment]
Fix in master. Closing!
