### ISSUE TITLE
Consul ELB with Self-Signed Cert

### ISSUE THREAD

**Issue by dcallao** [aws-quickstart/quickstart-hashicorp-consul#37]
The current setup does not have the Consul cluster behind an ELB. We wish to put the cluster behind public-facing ELB with a certificate from ACM and its URL part of the CFN outputs.

**Comment by avattathil** [comment]
@dcallao I am going to create two issue for this so we can split the work up

**Comment by Constantin07** [comment]
@dcallao given the fact that it's deployed in AWS why not use a proper ACM certificate instead of self-signed ?
Reason: self-signed cert won't be trusted by default ...

**Comment by dcallao** [comment]
Superseded by #39
