### ISSUE TITLE
Update Consul to Version (1.7.0)

### ISSUE THREAD

**Issue by avattathil** [aws-quickstart/quickstart-hashicorp-consul#40]
Update to Consul Version (1.6.1)

**Comment by avattathil** [comment]
Parametrize  The Version of Consul [Relevant Line here]( 
https://github.com/aws-quickstart/quickstart-hashicorp-consul/blob/develop/templates/quickstart-hashicorp-consul.template#L280)

**Comment by dcallao** [comment]
@avattathil The plan is now to upgrade Consul to lates version. This is now 1.7.0. See release: https://github.com/hashicorp/consul/releases/tag/v1.7.0-beta1

Can you change the title of this issue to `Update Consul to Version (1.7.0)`? Thx
