### ISSUE TITLE
Reconcile Documentation

### ISSUE THREAD

**Issue by dcallao** [aws-quickstart/quickstart-hashicorp-consul#42]
We wish to reconcile both the repo README and the landing page docs

**Comment by avattathil** [comment]
Can you update the readme the consul connect documentation. @gargana can you please open an email thread with the tech writers so we can make the update to the word doc (basically remove the old outdated information)

**Comment by dcallao** [comment]
@avattathil Yes. I will start working on the README. Thanks!
