### ISSUE TITLE
bootstrap_expect on consul_server_bootstrap.sh

### ISSUE THREAD

**Issue by cagriy** [aws-quickstart/quickstart-hashicorp-consul#9]
I think there might be an issue here. Last two lines of consul_server_bootstrap.sh tries to update bootstrap_expect value in the base.json (not sure if further bootstrapping required), and also this line seems to be failing as CONSUL_EXPECT value does not get passed to this script on the first instance.

As a result, template builds consul cluster ok, but servers do not start consul successfully when they are rebooted, due to the typo (missing expect value) in base.json

**Comment by avattathil** [comment]
Fixed in https://github.com/aws-quickstart/quickstart-hashicorp-consul/commit/30f0f0af7e710310f71127b494357c5ee60ff8c2

Thanks
